### ISSUE TITLE
Not able to return a plain boolean as a response

### ISSUE THREAD

**Issue by joskfg** [hkarlstrom/openapi-validation-middleware#9]
When I try to validate a response like this one:
```
responses: {
  200: {
    description: "Program replaced",
    content: {
      application/json: {
        schema: {
          type: "boolean"
        },
        example: true
     }
    }
  }
}
```

I traced the error and located in `/vendor/hkarlstrom/openapi-validation-middleware/src/OpenApiValidation.php:359`
```
private function validateObject(array $schema, array $value) : array
```

That method expects to always receive an array. It should be mixed because it could be a dimple string or in my case a simple boolean.

**Comment by francescozanoni** [comment]
Hi,
as far as I know, a scalar value cannot be returned as JSON response because the minimal JSON structure is an object or an array, as described on JSON's main page https://www.json.org .

If you have a look at OAS 3 examples (https://swagger.io/specification/#responseObject), you can see a similar situation (string instead of boolean, in this case):
````json
{
  "description": "A simple string response",
  "content": {
    "text/plain": {
      "schema": {
        "type": "string"
      }
    }
  }
}
````
Please correct me if I'm wrong, of course.

**Comment by hkarlstrom** [comment]
As far as I understand @francescozanoni is correct :) So I'll just close this isse.
